language: ruby
cache: bundle
rvm:
  - 2.5.0
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database auth0app_test;' -U postgres
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake